# Generated by Django 4.1.1 on 2022-11-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_profile_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_info',
            new_name='bio',
        ),
    ]
