# Generated by Django 4.1.1 on 2022-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_rename_profile_info_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='b',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
