# Generated by Django 4.1.1 on 2022-11-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_remove_profile_bio_profile_b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='b',
            new_name='bio',
        ),
    ]
