# Generated by Django 4.1.1 on 2022-11-16 22:51

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_rename_b_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='blank-profile-image.jpg', null=True, upload_to=authy.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
