# Generated by Django 4.1.1 on 2022-11-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_remove_profile_bio_profile_profile_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_info',
            new_name='bio',
        ),
    ]
