name: serve_link
description: "ServeLink connects customers with trusted service providers, making it easy to discover services, submit requests, and manage service needs in one place."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  firebase_storage: ^13.6.0

  # Media
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/servelink_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/servelink_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/servelink_logo.png"
  remove_alpha_ios: true