// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJrWp26cBcD5HwTCMZAfxdTO09vtAOYR0',
    appId: '1:85632166352:web:798f124c5773e993af71d5',
    messagingSenderId: '85632166352',
    projectId: 'servelink-app2',
    authDomain: 'servelink-app2.firebaseapp.com',
    storageBucket: 'servelink-app2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_62MyKw2NSwWpGAnSMMQpaZ1GRTz671g',
    appId: '1:85632166352:android:bd23af20ec3492fcaf71d5',
    messagingSenderId: '85632166352',
    projectId: 'servelink-app2',
    storageBucket: 'servelink-app2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD15SlIMCjiQVHzfszQ-08MstYt-7uI-aA',
    appId: '1:85632166352:ios:38537987f9e4074daf71d5',
    messagingSenderId: '85632166352',
    projectId: 'servelink-app2',
    storageBucket: 'servelink-app2.firebasestorage.app',
    iosBundleId: 'com.acetech.serveLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD15SlIMCjiQVHzfszQ-08MstYt-7uI-aA',
    appId: '1:85632166352:ios:38537987f9e4074daf71d5',
    messagingSenderId: '85632166352',
    projectId: 'servelink-app2',
    storageBucket: 'servelink-app2.firebasestorage.app',
    iosBundleId: 'com.acetech.serveLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJrWp26cBcD5HwTCMZAfxdTO09vtAOYR0',
    appId: '1:85632166352:web:a69622d72c856496af71d5',
    messagingSenderId: '85632166352',
    projectId: 'servelink-app2',
    authDomain: 'servelink-app2.firebaseapp.com',
    storageBucket: 'servelink-app2.firebasestorage.app',
  );
}
