# Generated by Django 4.2.26 on 2025-11-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='short_name',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
