# Generated by Django 4.2.26 on 2025-11-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_schoolclass_description_schoolclass_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('desired_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.schoolclass')),
            ],
        ),
    ]
